### ISSUE TITLE
Search tool not accessible to players. 

### ISSUE THREAD

**Issue by franckflo** [Khaali-dev/fullsearch#4]
I noticed that the search field under the chat input bar is not visible from the player side. Would it be possible to add that as an option ? Also, the magnifying glass  icon in the bar is not visible to players either when switching that option.

Also, when switching to the toolbar icon, clicking on the magnifying glass does not open an input window. Nothing seems to happen.

**Comment by Khaali-dev** [comment]
- The search tool is for now intended for GM only, but I'll work on a version that can be opened to players while respecting access rights.
- As for other icons in the left toolbar, clicking on it will open a second toolbar, which will have another looking glass icon. Clicking on it will open the search dialog.

**Comment by franckflo** [comment]
Perfect, I found the second icon. That works :). Good news for a future Player-compatible version. Thanks!

**Comment by SLinxTheFox** [comment]
Just saying here I second this. Being able to quickly search for rules and house rules that are in journals would be amazing for my players
